### ISSUE TITLE
Improvement in Navbar and Our menu

### ISSUE THREAD

**Issue by hvb24** [sanskar0901/Fashion-Restaurant#14]
Wanted to imporve Navbar as it is not looking attractive and also Our menu as it is not arranged in a Proper way.
@sanskar0901 Can I work on it?

**Comment by sanskar0901** [comment]
> Wanted to improve Navbar as it is not looking attractive and also Our menu as it is not arranged in a proper way. @sanskar0901 Can I work on it?

yes
