### ISSUE TITLE
Hey, can I add more style to it and can make it look more appealing. If yes, please assign me, I want to contribute in it.

### ISSUE THREAD

**Issue by yamini3707** [sanskar0901/Fashion-Restaurant#3]
Hey, Can I add more style to it and make it look more appealing. If yes, Please assign me.

**Comment by sanskar0901** [comment]
> Hey, Can I add more style to it and make it look more appealing. If yes, Please assign me.

Hi Yamini it would be great if you could help me enhance my website and make it look more appealing to the user

**Comment by sanskar0901** [comment]
> Could You please assign this issue to me

yeah
